"""Step 08: Fold Data/Defi/ into Data/DefiLlama/ with topical subfolders.

Target layout:
  Data/DefiLlama/
    README.md
    TVL/Daily/, TVL/Weekly/, TVL/Snapshot/     (was CSV/Daily|Weekly|Snapshot)
    Stablecoins/        (stablecoin_mcap*, stablecoins*, *-chains.csv)
    ETFs/               (etf-*)
    RWA/                (rwa-*)
    ChainMetrics/       (all_metrics*, ethereum_metrics*, solana_metrics*)
    CEX/                (cex_net_inflows*)
    DATs/               (dat-institutions.csv)
    _raw_parts/         (moved as-is from Defi/_raw_parts)

After this script runs:
- Data/Defi/ is removed entirely.
- Data/DefiLlama/CSV/ is renamed to Data/DefiLlama/TVL/.

This script is idempotent: re-running it after everything has already been moved is a no-op.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import DATA_DIR, log, rel_to_data  # noqa: E402


DEFI_SRC = DATA_DIR / "Defi"
LLAMA_DST = DATA_DIR / "DefiLlama"
CSV_DIR_OLD = LLAMA_DST / "CSV"
TVL_DIR_NEW = LLAMA_DST / "TVL"

# filename patterns -> target subfolder
PATTERN_TO_SUBDIR: list[tuple[str, str]] = [
    ("stablecoin_mcap_by_defillama_id__daily.csv", "Stablecoins"),
    ("stablecoin_mcap_id_to_name.csv", "Stablecoins"),
    ("stablecoins.csv", "Stablecoins"),
    ("stablecoins-chains.csv", "Stablecoins"),
    ("etf-history.csv", "ETFs"),
    ("etf-overview.csv", "ETFs"),
    ("dat-institutions.csv", "DATs"),
    ("cex_net_inflows_by_exchange__daily.csv", "CEX"),
]

PREFIX_TO_SUBDIR: list[tuple[str, str]] = [
    ("rwa-", "RWA"),
    ("all_metrics_", "ChainMetrics"),
    ("ethereum_metrics_", "ChainMetrics"),
    ("solana_metrics_", "ChainMetrics"),
    ("bitcoin_metrics_", "ChainMetrics"),
]


def classify(name: str) -> str | None:
    for exact, sub in PATTERN_TO_SUBDIR:
        if name == exact:
            return sub
    for prefix, sub in PREFIX_TO_SUBDIR:
        if name.startswith(prefix):
            return sub
    return None


def _safe_move(src: Path, dst: Path, log_lines: list[str]) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        if src.resolve() == dst.resolve():
            return
        # Destination already exists — this is expected on re-runs.
        log_lines.append(f"- SKIP (dst exists): `{rel_to_data(src)}` -> `{rel_to_data(dst)}`")
        return
    shutil.move(str(src), str(dst))
    log_lines.append(f"- moved `{rel_to_data(src)}` -> `{rel_to_data(dst)}`")


def rename_csv_to_tvl(lines: list[str]) -> None:
    """Rename Data/DefiLlama/CSV/ -> Data/DefiLlama/TVL/."""
    if TVL_DIR_NEW.exists() and not CSV_DIR_OLD.exists():
        lines.append("- `DefiLlama/CSV/` already renamed to `DefiLlama/TVL/` (idempotent).")
        return
    if not CSV_DIR_OLD.exists():
        lines.append("- `DefiLlama/CSV/` not found; skipping rename.")
        return
    if TVL_DIR_NEW.exists():
        # Shouldn't happen, but merge content just in case.
        lines.append("- WARNING: both `CSV/` and `TVL/` exist; merging CSV into TVL.")
        for p in CSV_DIR_OLD.rglob("*"):
            if p.is_file():
                rel = p.relative_to(CSV_DIR_OLD)
                _safe_move(p, TVL_DIR_NEW / rel, lines)
        # Clean up empty CSV
        for d in sorted(CSV_DIR_OLD.rglob("*"), reverse=True):
            if d.is_dir() and not any(d.iterdir()):
                d.rmdir()
        if CSV_DIR_OLD.exists() and not any(CSV_DIR_OLD.iterdir()):
            CSV_DIR_OLD.rmdir()
    else:
        CSV_DIR_OLD.rename(TVL_DIR_NEW)
        lines.append(f"- renamed `DefiLlama/CSV/` -> `DefiLlama/TVL/`.")


def move_defi_contents(lines: list[str]) -> None:
    """Move everything out of Data/Defi/ into Data/DefiLlama/ subfolders."""
    if not DEFI_SRC.exists():
        lines.append("- `Data/Defi/` not found; nothing to consolidate.")
        return

    # 1. CSVs at the top of Defi/
    uncategorized: list[Path] = []
    for p in sorted(DEFI_SRC.glob("*.csv")):
        sub = classify(p.name)
        if sub is None:
            uncategorized.append(p)
            continue
        _safe_move(p, LLAMA_DST / sub / p.name, lines)

    # 2. Defi/_raw_parts/ tree -> DefiLlama/_raw_parts/
    raw_src = DEFI_SRC / "_raw_parts"
    if raw_src.is_dir():
        for p in sorted(raw_src.rglob("*")):
            if p.is_file():
                rel = p.relative_to(raw_src)
                _safe_move(p, LLAMA_DST / "_raw_parts" / rel, lines)

    # 3. Drop the old per-folder READMEs (they will be regenerated by step 06).
    for md in list(DEFI_SRC.rglob("*.md")):
        if md.is_file():
            lines.append(f"- removing old `{rel_to_data(md)}` (will be regenerated)")
            md.unlink()

    # 4. Any other files (shouldn't happen, but if so keep them in _uncategorized/)
    for p in sorted(DEFI_SRC.rglob("*")):
        if p.is_file():
            lines.append(f"- UNCATEGORIZED leftover `{rel_to_data(p)}`, leaving in place for manual review")

    # 5. Remove empty dirs under Defi/
    for d in sorted(DEFI_SRC.rglob("*"), reverse=True):
        if d.is_dir() and not any(d.iterdir()):
            try:
                d.rmdir()
            except OSError:
                pass

    if DEFI_SRC.exists() and not any(DEFI_SRC.iterdir()):
        DEFI_SRC.rmdir()
        lines.append("- removed empty `Data/Defi/` folder.")
    elif DEFI_SRC.exists():
        remaining = [rel_to_data(p) for p in DEFI_SRC.rglob("*")]
        lines.append(f"- `Data/Defi/` still has {len(remaining)} remaining entries: {remaining[:5]}")

    if uncategorized:
        lines.append("- UNCATEGORIZED top-level CSVs (left in place):")
        for p in uncategorized:
            lines.append(f"  - `{rel_to_data(p)}`")


def main() -> None:
    lines: list[str] = ["### Consolidation moves", ""]
    rename_csv_to_tvl(lines)
    lines.append("")
    move_defi_contents(lines)
    log("Step 08 — consolidate Defi into DefiLlama", lines)
    print("Step 08 done.")


if __name__ == "__main__":
    main()
