"""Step 11: Flatten `Data/Farside ETF Data/`.

Before:
    Farside ETF Data/
      BTC/{bitcoin_etf_flow_all_data.csv, README.md}
      ETH/{ethereum_etf_flow_all_data.csv, README.md}
      SOL/{solana_etf_flow_all_data.csv, README.md}
      Farside_ETF_Data_Summary.txt

After:
    Farside ETF Data/
      farside_btc_etf_flows__daily.csv
      farside_eth_etf_flows__daily.csv
      farside_sol_etf_flows__daily.csv
      Farside_ETF_Data_Summary.txt      (preserved verbatim)
      README.md                         (single consolidated README)

Removes the now-empty BTC/, ETH/, SOL/ subfolders and their per-asset READMEs.
Idempotent: re-runs are no-ops once the flat layout exists.

The consolidated README is regenerated by this script directly (it does NOT
wait for 06_build_inventory, so the folder is complete after this step).
06_build_inventory will later OVERWRITE it with the unified template —
that is intentional.
"""
from __future__ import annotations

import io
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import DATA_DIR, log, rel_to_data  # noqa: E402

FARSIDE = DATA_DIR / "Farside ETF Data"

FILE_MAP: dict[str, str] = {
    "BTC/bitcoin_etf_flow_all_data.csv":  "farside_btc_etf_flows__daily.csv",
    "ETH/ethereum_etf_flow_all_data.csv": "farside_eth_etf_flows__daily.csv",
    "SOL/solana_etf_flow_all_data.csv":   "farside_sol_etf_flows__daily.csv",
}


def _write_csv(df: pd.DataFrame, path: Path) -> None:
    buf = io.StringIO()
    df.to_csv(buf, index=False, lineterminator="\n")
    path.write_bytes(buf.getvalue().encode("utf-8"))


def _normalize(df: pd.DataFrame) -> pd.DataFrame:
    cols = list(df.columns)
    # Accept either `date` or `Date` (older exports had the latter).
    first = cols[0]
    if first.lower() != "date":
        return df
    if first != "date":
        df = df.rename(columns={first: "date"})
    df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True).dt.strftime("%Y-%m-%d")
    df = df.dropna(subset=["date"]).drop_duplicates(subset=["date"]).sort_values("date")
    return df.reset_index(drop=True)


def _build_readme(summaries: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    rows = []
    for s in summaries:
        rows.append(
            f"| `{s['file']}` | {s['asset']} | {s['date_range']} | {s['rows']:,} | {s['columns']} |"
        )
    sample_blocks = []
    for s in summaries:
        sample_blocks.append(f"**`{s['file']}`**\n\n```csv\n{s['sample']}\n```\n")
    return (
        "# Farside ETF Data\n"
        "\n"
        "**Source**: https://farside.co.uk/ (Bitcoin, Ethereum, and Solana spot-ETF flow pages)  \n"
        "**Fetcher**: `tools/fetch_farside_etf_csv.py`\n"
        "\n"
        "Daily US$m net flows into US spot ETFs by issuer, with a `Total` column per asset. "
        "Empty cells correspond to `-` on the Farside page (no flow / not applicable); outflows are negative numbers.\n"
        "\n"
        "## Date convention\n"
        "\n"
        "First column is `date` (ISO `YYYY-MM-DD`, NYSE trading-day cadence — weekends and market holidays absent, ascending).\n"
        "\n"
        "## Files\n"
        "\n"
        "| File | Asset | Date range | Rows | Columns |\n"
        "| --- | --- | --- | ---: | --- |\n"
        + "\n".join(rows)
        + "\n\n"
        "### Ticker legend\n"
        "\n"
        "- BTC ETFs: `IBIT` (BlackRock), `FBTC` (Fidelity), `BITB` (Bitwise), `ARKB` (ARK21Shares), "
        "`BTCO` (Invesco), `EZBC` (Franklin), `BRRR` (Valkyrie), `HODL` (VanEck), `BTCW` (WisdomTree), "
        "`MSBT` (Merrill Short BTC), `GBTC` (Grayscale), `BTC` (Grayscale Mini BTC), `Total` (daily sum).\n"
        "- ETH ETFs: `ETHA` (BlackRock), `ETHB` (Grayscale Mini ETH), `FETH` (Fidelity), "
        "`ETHW` (Bitwise), `TETH` (21Shares — legacy ticker), `ETHV` (VanEck), `QETH` (Invesco), "
        "`EZET` (Franklin), `ETHE` (Grayscale), `ETH` (Grayscale Mini ETH), `Total`.\n"
        "- SOL ETFs: `BSOL` (Bitwise), `VSOL` (VanEck), `FSOL` (Fidelity), `TSOL` (21Shares), "
        "`SOEZ` (Franklin), `GSOL` (Grayscale), `Total`.\n"
        "\n"
        "## Sample rows (first 2 rows per file)\n"
        "\n"
        + "\n".join(sample_blocks)
        + "\n"
        "## Regenerating from the live site\n"
        "\n"
        "```bash\n"
        "python tools/fetch_farside_etf_csv.py\n"
        "```\n"
        "\n"
        "This re-downloads the three pages from Farside and overwrites the three CSVs in-place. "
        "Re-run `tools/data_curation/04_normalize_dates.py` afterwards if the date column format changes.\n"
        "\n"
        "---\n"
        f"_Auto-generated on {now} by `tools/data_curation/11_flatten_farside.py`. "
        "`tools/data_curation/06_build_inventory.py` will overwrite this with the unified project template._\n"
    )


def main() -> None:
    if not FARSIDE.is_dir():
        print(f"Farside dir not found: {FARSIDE}")
        return

    lines: list[str] = []
    summaries: list[dict] = []

    for rel_src, dst_name in FILE_MAP.items():
        src = FARSIDE / rel_src
        dst = FARSIDE / dst_name
        if dst.is_file() and not src.is_file():
            lines.append(f"- `{dst_name}` already at top level; skipped.")
        elif src.is_file() and not dst.is_file():
            df = pd.read_csv(src)
            df = _normalize(df)
            _write_csv(df, dst)
            src.unlink()
            lines.append(f"- moved `{rel_to_data(src)}` -> `{rel_to_data(dst)}` ({len(df):,} rows).")
        elif src.is_file() and dst.is_file():
            # Both exist — keep dst, quarantine src (shouldn't normally happen).
            src.unlink()
            lines.append(f"- `{dst_name}` already exists; deleted stray `{rel_to_data(src)}`.")
        else:
            lines.append(f"- NEITHER `{rel_src}` nor `{dst_name}` found (nothing to do).")

    # Collect summaries for README.
    asset_map = {
        "farside_btc_etf_flows__daily.csv": "Bitcoin (BTC)",
        "farside_eth_etf_flows__daily.csv": "Ethereum (ETH)",
        "farside_sol_etf_flows__daily.csv": "Solana (SOL)",
    }
    for fname, asset in asset_map.items():
        p = FARSIDE / fname
        if not p.is_file():
            continue
        df = pd.read_csv(p)
        drange = f"{df['date'].iloc[0]} .. {df['date'].iloc[-1]}" if len(df) else "—"
        sample = df.head(2).to_csv(index=False, lineterminator="\n").strip()
        summaries.append({
            "file": fname,
            "asset": asset,
            "date_range": drange,
            "rows": len(df),
            "columns": ", ".join(f"`{c}`" for c in df.columns),
            "sample": sample,
        })

    # Delete the now-empty subfolders (and their per-asset READMEs).
    for sub in ("BTC", "ETH", "SOL"):
        subdir = FARSIDE / sub
        if subdir.is_dir():
            try:
                shutil.rmtree(subdir)
                lines.append(f"- removed `{rel_to_data(subdir)}/`.")
            except OSError as e:
                lines.append(f"- could NOT remove `{rel_to_data(subdir)}/`: {e}")

    # Write single consolidated README.
    (FARSIDE / "README.md").write_text(_build_readme(summaries), encoding="utf-8")
    lines.append(f"- wrote consolidated `Farside ETF Data/README.md` covering {len(summaries)} files.")

    log("Step 11 — flatten Farside", lines)
    print(f"Step 11 done: {len(summaries)} files at top level.")


if __name__ == "__main__":
    main()
